name = "identify-provider-extension"
client_id = "04211a6555924a300119d2ab22b99342"
application_url = "https://shopify-test.acquaintsoft.com"
embedded = true

[access_scopes]
# Read customer data
scopes = "read_customers"

[webhooks]
api_version = "2023-01"

[auth]
redirect_urls = [
  "https://shopify-test.acquaintsoft.com/shopify/callback",
  "https://shopify-test.acquaintsoft.com/identify"
]

[app_extensions]
[[app_extensions.targeting]]
target = "admin.customer.list"
module = "./app-extension.js" 